# Generated by Django 5.2.3 on 2025-06-20 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeout',
            name='visitor',
        ),
        migrations.DeleteModel(
            name='TimeIn',
        ),
        migrations.DeleteModel(
            name='TimeOut',
        ),
        migrations.DeleteModel(
            name='Visitor',
        ),
    ]
